sudo: false
language: ruby
rvm:
  - 2.0.0

bundler_args: --path=vendor/bundle --without heroku

before_script:
  - sh -c "psql -c 'create database ffcrm_vend_test;' -U postgres"
  - sh -c "RAILS_ENV=test bundle exec rake db:schema:load"

# Run specs
script: "bundle exec rake"
