language: ruby
rvm:
  - 2.0.0

env:
  - DB=postgres

bundler_args: --path=vendor/bundle --without heroku

before_script:
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database ffcrm_vend_test;' -U postgres; fi"

# Run specs
script: "bundle exec rake"
